kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    settings:
      mtu: 1450
      context: docker
      dockerfile: docker/Dockerfile
      tags:
        - ubuntu-22
        - ubuntu
        - latest
      repo: maoxuner/yadst
      username: maoxuner
      password:
        from_secret: docker-password

  - name: notify
    image: lddsb/drone-dingtalk-message:1.2.8
    settings:
      success_token:
        from_secret: dingtalk-success-token
      success_secret:
        from_secret: dingtalk-success-secret
      failure_token:
        from_secret: dingtalk-failure-token
      failure_secret:
        from_secret: dingtalk-failure-secret
      lang: zh_CN
      msg_type: markdown
      msg_at_all: false
    commands:
      - set -e
      - |
        if [ $DRONE_BUILD_STATUS = "success" ]; then
            export PLUGIN_TOKEN=$PLUGIN_SUCCESS_TOKEN
            export PLUGIN_SECRET=$PLUGIN_SUCCESS_SECRET
        else
            export PLUGIN_TOKEN=$PLUGIN_FAILURE_TOKEN
            export PLUGIN_SECRET=$PLUGIN_FAILURE_SECRET
        fi
      - /bin/drone-dingtalk
    when:
      status:
        - success
        - failure
volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

---
kind: secret
name: docker-password
get:
  path: drone-docker-registry
  name: password

---
kind: secret
name: dingtalk-success-token
get:
  path: drone-dingtalk-robot
  name: success_token

---
kind: secret
name: dingtalk-success-secret
get:
  path: drone-dingtalk-robot
  name: success_secret

---
kind: secret
name: dingtalk-failure-token
get:
  path: drone-dingtalk-robot
  name: failure_token

---
kind: secret
name: dingtalk-failure-secret
get:
  path: drone-dingtalk-robot
  name: failure_secret
