services:
  master-shard:
    image: yadst-runtime
    build: .
    working_dir: /opt/dst/game/bin64
    entrypoint: ./dontstarve_dedicated_server_nullrenderer_x64
    command:
      - -ugc_directory
      - /opt/dst/game/ugc_mods
      - -persistent_storage_root
      - /opt/dst/data
      - -conf_dir
      - DoNotStarveTogether
      - -cluster
      - MyDediServer
      - -shard
      - Master
      - -skip_update_server_mods
    volumes:
      - ./server/game:/opt/dst/game
      - ./server/data:/opt/dst/data
    ports:
      - 11000-11001
      - 11000-11001/udp

  caves-shard:
    image: yadst-runtime
    build: .
    working_dir: /opt/dst/game/bin64
    entrypoint: ./dontstarve_dedicated_server_nullrenderer_x64
    command:
      - -ugc_directory
      - /opt/dst/game/ugc_mods
      - -persistent_storage_root
      - /opt/dst/data
      - -conf_dir
      - DoNotStarveTogether
      - -cluster
      - MyDediServer
      - -shard
      - Caves
      - -skip_update_server_mods
    volumes_from:
      - master-shard
    network_mode: service:master-shard
