version: "3"
services:
  master:
    image: yadst
    build: .
    environment:
      LANGUAGE: zh
      CLUSTER_TOKEN: ${CLUSTER_TOKEN}
      WORLD_PRESET: SURVIVAL_TOGETHER
      MODS: "1438233888"
      SERVER_PORT: "10999"
      SHARD_ENABLE: "true"
      SHARD_NAME: Master
      SHARD_ID: "1"
      SHARD_IS_MASTER: "true"
      SHARD_CLUSTER_KEY: secret
    volumes:
      - ./data/storage:/storage:rw
      - ./data/server:/home/steam/dst-dedicated:rw
    networks:
      default:
          ipv4_address: 172.32.1.1
    ports:
      - 10999:10999

  caves:
    image: yadst
    build: .
    environment:
      LANGUAGE: zh
      CLUSTER_TOKEN: ${CLUSTER_TOKEN}
      WORLD_PRESET: DST_CAVE
      MODS: "1438233888"
      SERVER_PORT: "10998"
      SHARD_ENABLE: "true"
      SHARD_NAME: Caves
      SHARD_ID: "2"
      SHARD_IS_MASTER: "false"
      SHARD_MASTER_IP: "172.32.1.1"
      SHARD_CLUSTER_KEY: secret
    volumes:
      - ./data/storage:/storage:rw
      - ./data/server:/home/steam/dst-dedicated:rw
    networks:
      default:
          ipv4_address: 172.32.1.2
    ports:
      - 10998:10998

  others:
    image: yadst
    build: .
    environment:
      LANGUAGE: zh
      CLUSTER_TOKEN: ${CLUSTER_TOKEN}
      WORLD_PRESET: SURVIVAL_TOGETHER
      MODS: "1438233888"
      SERVER_PORT: "10997"
      SHARD_ENABLE: "true"
      SHARD_NAME: Others
      SHARD_ID: "3"
      SHARD_IS_MASTER: "false"
      SHARD_MASTER_IP: "172.32.1.1"
      SHARD_CLUSTER_KEY: secret
    volumes:
      - ./data/storage:/storage:rw
      - ./data/server:/home/steam/dst-dedicated:rw
    networks:
      default:
          ipv4_address: 172.32.1.3
    ports:
      - 10997:10997

networks:
  default:
    ipam:
      config:
        - subnet: 172.32.0.0/16
