version: '1.0'
name: build
displayName: 构建
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: default
    displayName: 默认
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: b34f1b10-ba3e-013b-91d0-1ecb49bdcebb
        tag: maoxuner/yadst:latest
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify:
          - certificate: 1bf0a710-303f-013c-0f4d-4afef757e4a0
            events:
              - success
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
          - certificate: 0a844880-303f-013c-ccf7-0e601ba24b3a
            events:
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
